### ISSUE TITLE
[问题]标题Application startup failed. Exiting.

### ISSUE THREAD

**Issue by LaffeyLa** [zhulinyv/NJS#2]
### 确认

- 我的Bot版本已更新到最新，且已尝试使用`poetry install`更新依赖库
- 我已查阅[文档-常见问题](https://docs.paimon.cherishmoon.fun/question.html)，无相关解决方案
- 我已确认[issue](https://github.com/CMHopeSunshine/LittlePaimon/issues)中没有类似的问题或仍然得不到解决

### 环境信息

- 系统版本: Ubantu20.04
- Python版本: 3.9.10

### 问题描述

进入虚拟环境后nb run,最后出现Application startup failed. Exiting.

### 问题截图

03-11 11:07:58 [SUCCESS] LittlePaimon | [数据库]连接成功
03-11 11:07:58 [SUCCESS] LittlePaimon | [插件管理器]初始化完成
03-11 11:07:58 [INFO] LittlePaimon | [资源检查]开始检查资源
03-11 11:07:58 [WARNING] nonebot_plugin_memes | Error downloading https://ghproxy.com/https://raw.githubusercontent.com/noneplugin/nonebot-plugin-memes/v0.3.x/resources/thumbs/shuifandui.jpg, retry 1/3: 
03-11 11:07:58 [WARNING] LittlePaimon | [资源检查]读取资源列表失败，请尝试更换github资源地址
03-11 11:07:58 [INFO] LittlePaimon | [Playwright]浏览器初始化成功
03-11 11:07:59 [ERROR] uvicorn | Traceback (most recent call last):
  File "/home/benson/.cache/pypoetry/virtualenvs/njs-TuGSxenq-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 671, in lifespan
    async with self.lifespan_context(app):
  File "/home/benson/.cache/pypoetry/virtualenvs/njs-TuGSxenq-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 566, in __aenter__
    await self._router.startup()
  File "/home/benson/.cache/pypoetry/virtualenvs/njs-TuGSxenq-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 648, in startup
    await handler()
  File "/home/benson/NJS/./LittlePaimon/plugins/Paimon_Chat/__init__.py", line 103, in load_voice
    voice_list = await load_json_from_url('https://static.cherishmoon.fun/LittlePaimon/voice/voice_list.json', path)
  File "/home/benson/.cache/pypoetry/virtualenvs/njs-TuGSxenq-py3.10/lib/python3.10/site-packages/littlepaimon_utils/files.py", line 73, in load_json_from_url
    data = resp.json()
  File "/home/benson/.cache/pypoetry/virtualenvs/njs-TuGSxenq-py3.10/lib/python3.10/site-packages/httpx/_models.py", line 1516, in json
    return jsonlib.loads(self.content.decode(encoding), **kwargs)
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

03-11 11:07:59 [ERROR] uvicorn | Application startup failed. Exiting.

### 复现步骤[可选]

描述问题复现过程...

**Comment by zhulinyv** [comment]
请将 `.\NJS\plugins\Paimon_Chat` 目录下的 `__init__.py` 改名为 `init__.py` 后重试。

**Comment by LaffeyLa** [comment]
> 请将 `.\NJS\plugins\Paimon_Chat` 目录下的 `__init__.py` 改名为 `init__.py` 后重试。

ok了，我把starlette插件卸载重装就ok了

**Comment by DuuuLu** [comment]
> > 请将  目录下的  改名为  后重试。`.\NJS\plugins\Paimon_Chat``__init__.py``init__.py`
> 
> ok了，我把starlette插件卸载重装就ok了

你好！我也遇到这个问题了，请问starlette的目录在哪里啊？

**Comment by zhulinyv** [comment]
> > > 请将  目录下的  改名为  后重试。`` .\NJS\plugins\Paimon_Chat``__init__.py``init__.py ``
> > 
> > 
> > ok了，我把starlette插件卸载重装就ok了
> 
> 你好！我也遇到这个问题了，请问starlette的目录在哪里啊？

~~在 NJS 目录依次执行：
`poetry run pip uninstall starlette`
`poetry run pip install starlette`~~

**Comment by zhulinyv** [comment]
https://github.com/zhulinyv/NJS/commit/306799fe55dc17caa3bd2fdec03112dc59c6f82b
