### ISSUE TITLE
🐛setu4报错力

### ISSUE THREAD

**Issue by MaboroneSeika** [zhulinyv/NJS#25]
### 确认

- 我的Bot版本已更新到最新，且已尝试运行 `poetry install` 更新依赖库
- 我已查阅[文档-常见问题](https://github.com/zhulinyv/NJS#readme)，无相关解决方案
- 我已确认[issue](https://github.com/zhulinyv/NJS/issues)中没有类似的问题或仍然得不到解决

### 环境信息

- 系统版本: win11
- Python版本: 3.10
- Nonebot2版本: 默认

### 问题描述

使用时报错

### 问题截图
07-12 20:49:03 [ERROR] nonebot | Running Matcher(type='message', module=src.plugins.nonebot_plugin_setu4) failed.
Traceback (most recent call last):
  File "G:\NJS-Bot\bot.py", line 41, in <module>
    nonebot.run(app="__mp_main__:app", access_log=False)
  File "C:\Users\shubi\AppData\Local\pypoetry\Cache\virtualenvs\njs-06ksLelh-py3.10\lib\site-packages\nonebot\__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\shubi\AppData\Local\pypoetry\Cache\virtualenvs\njs-06ksLelh-py3.10\lib\site-packages\nonebot\drivers\fastapi.py", line 198, in run
    uvicorn.run(
  File "C:\Users\shubi\AppData\Local\pypoetry\Cache\virtualenvs\njs-06ksLelh-py3.10\lib\site-packages\uvicorn\main.py", line 578, in run
    server.run()
  File "C:\Users\shubi\AppData\Local\pypoetry\Cache\virtualenvs\njs-06ksLelh-py3.10\lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\software\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\software\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\software\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\software\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\software\Python310\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "C:\software\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\shubi\AppData\Local\pypoetry\Cache\virtualenvs\njs-06ksLelh-py3.10\lib\site-packages\nonebot\message.py", line 467, in check_and_run_matcher
    await _run_matcher(
  File "C:\Users\shubi\AppData\Local\pypoetry\Cache\virtualenvs\njs-06ksLelh-py3.10\lib\site-packages\nonebot\message.py", line 419, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\shubi\AppData\Local\pypoetry\Cache\virtualenvs\njs-06ksLelh-py3.10\lib\site-packages\nonebot\internal\matcher\matcher.py", line 753, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\shubi\AppData\Local\pypoetry\Cache\virtualenvs\njs-06ksLelh-py3.10\lib\site-packages\nonebot\internal\matcher\matcher.py", line 728, in simple_run
    await handler(
  File "C:\Users\shubi\AppData\Local\pypoetry\Cache\virtualenvs\njs-06ksLelh-py3.10\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "G:\NJS-Bot\src\plugins\nonebot_plugin_setu4\__init__.py", line 85, in _
    args = list(state["_matched_groups"])
KeyError: '_matched_groups'

### 复现步骤

使用此插件

**Comment by zhulinyv** [comment]
我不确定是什么导致的，已尝试更新。

**Comment by MaboroneSeika** [comment]
> 我不确定是什么导致的，已尝试更新。

修好了！~
